server/ema/urls.py
from django.conf.urls import url

from ema.views import best_countries, ema_quotas

urlpatterns = [
    url(r"^countries/best/$", best_countries, name="best_countries"),
    url(r"^quotas/$", ema_quotas, name="ema_quotas"),
]

server/mahjong_portal/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.views.decorators.cache import cache_page

from mahjong_portal.sitemap import (
    ClubSitemap,
    EMATournamentListSitemap,
    PlayerSitemap,
    RatingSitemap,
    StaticSitemap,
    TournamentAnnouncementSitemap,
    TournamentListSitemap,
    TournamentSitemap,
)
from online.views import finish_game_api
from website.views import players_api

sitemaps = {
    "static": StaticSitemap,
    "tournament_list": TournamentListSitemap,
    "ema_tournaments_list": EMATournamentListSitemap,
    "tournament_details": TournamentSitemap,
    "tournament_announcement_details": TournamentAnnouncementSitemap,
    "club_details": ClubSitemap,
    "player_details": PlayerSitemap,
    "rating_details": RatingSitemap,
}

urlpatterns = [
    url(r"^admin/", include(admin.site.urls[:2])),
    url(r"^i18n/", include("django.conf.urls.i18n")),
    url(
        r"^sitemap\.xml$",
        cache_page(86400)(sitemap),
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    url("^api/v0/players/$", players_api),
    url("^api/v0/finish_game_api/$", finish_game_api),
    url(r"^online/", include("online.urls")),
]

urlpatterns += i18n_patterns(
    url(r"", include("website.urls")),
    url(r"^rating/", include("rating.urls")),
    url(r"^tournaments/", include("tournament.urls")),
    url(r"^clubs/", include("club.urls")),
    url(r"^players/", include("player.urls")),
    url(r"^tenhou/", include("player.tenhou.urls")),
    url(r"^ms/", include("player.mahjong_soul.urls")),
    url(r"^system/", include("system.urls")),
    url(r"^ema/", include("ema.urls")),
    url(r"^account/", include("account.urls")),
    url(r"^wiki/", include("wiki.urls")),
    url(r"^league/", include("league.urls")),
)

server/player/tenhou/urls.py
from django.conf.urls import url

from player.tenhou.views import (
    games_history,
    get_current_tenhou_games,
    get_current_tenhou_games_async,
    latest_yakumans,
    tenhou_accounts,
)

urlpatterns = [
    url(r"^games/history/(?P<year>\d+)/(?P<month>\d+)/(?P<day>\d+)/$", games_history, name="tenhou_games_history"),
    url(r"^games/history/$", games_history, name="tenhou_games_history"),
    url(r"^games/$", get_current_tenhou_games, name="get_current_tenhou_games"),
    url(r"^games/async/$", get_current_tenhou_games_async, name="get_current_tenhou_games_async"),
    url(r"^yakumans/$", latest_yakumans, name="latest_yakumans"),
    url(r"^accounts/$", tenhou_accounts, name="tenhou_accounts"),
]

server/player/tenhou/models.py
from datetime import timedelta

from django.db import models
from django.db.models import F
from django.utils.translation import gettext_lazy

from mahjong_portal.models import BaseModel
from player.models import Player
from utils.tenhou.points_calculator import FourPlayersPointsCalculator
from utils.tenhou.yakuman_list import YAKUMAN_CONST


class TenhouActiveNicknameManager(models.Manager):
    def get_queryset(self):
        queryset = super(TenhouActiveNicknameManager, self).get_queryset()
        return queryset.filter(is_active=True)


class TenhouNickname(BaseModel):
    objects = TenhouActiveNicknameManager()
    all_objects = models.Manager()

    player = models.ForeignKey(Player, on_delete=models.CASCADE, related_name="tenhou")

    tenhou_username = models.CharField(max_length=8)
    username_created_at = models.DateField()

    last_played_date = models.DateField(null=True, blank=True)

    is_main = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)

    def __unicode__(self):
        return self.tenhou_username

    class Meta:
        ordering = ["-username_created_at"]
        db_table = "player_tenhounickname"

    def four_players_aggregated_statistics(self):
        return self.aggregated_statistics.filter(game_players=TenhouAggregatedStatistics.FOUR_PLAYERS).first()

    def all_time_stat(self):
        return self.statistics.filter(stat_type=TenhouStatistics.ALL_TIME)

    def current_month_stat(self):
        return self.statistics.filter(stat_type=TenhouStatistics.CURRENT_MONTH)

    def latest_yakumans(self):
        return self.yakumans.order_by("-date")

    def prepare_latest_places(self):
        return list(
            reversed(self.game_logs.filter(game_players=TenhouGameLog.FOUR_PLAYERS).order_by("-game_date")[:20])
        )

    def rank_changes(self):
        return (
            self.game_logs.filter(game_players=TenhouGameLog.FOUR_PLAYERS)
            .exclude(rank=F("next_rank"))
            .order_by("game_date")
        )

    def pt_changes(self):
        last_rank_change_date = self.rank_changes().last()
        last_rank_change_date = last_rank_change_date.game_end_date if last_rank_change_date else None
        if not last_rank_change_date:
            return None
        return self.game_logs.filter(game_date__gte=last_rank_change_date)

    def dan_settings(self):
        return FourPlayersPointsCalculator.DAN_SETTINGS[self.get_rank_display()]

    def get_rank_display(self):
        stat = self.aggregated_statistics.filter(game_players=TenhouAggregatedStatistics.FOUR_PLAYERS).first()
        return stat.get_rank_display()


class TenhouAggregatedStatistics(models.Model):
    RANKS = [
        [0, "新人"],
        [1, "９級"],
        [2, "８級"],
        [3, "７級"],
        [4, "６級"],
        [5, "５級"],
        [6, "４級"],
        [7, "３級"],
        [8, "２級"],
        [9, "１級"],
        [10, "初段"],
        [11, "二段"],
        [12, "三段"],
        [13, "四段"],
        [14, "五段"],
        [15, "六段"],
        [16, "七段"],
        [17, "八段"],
        [18, "九段"],
        [19, "十段"],
        [20, "天鳳位"],
    ]

    FOUR_PLAYERS = 0
    THREE_PLAYERS = 1

    TYPES = [[FOUR_PLAYERS, "Four players"], [THREE_PLAYERS, "Three players"]]

    tenhou_object = models.ForeignKey(TenhouNickname, on_delete=models.CASCADE, related_name="aggregated_statistics")
    rank = models.PositiveSmallIntegerField(choices=RANKS, null=True, blank=True)
    rate = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    game_players = models.PositiveSmallIntegerField(choices=TYPES, null=True, blank=True)

    played_games = models.PositiveIntegerField(default=0)
    month_played_games = models.PositiveIntegerField(default=0)

    average_place = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    month_average_place = models.DecimalField(decimal_places=2, max_digits=10, default=0)

    pt = models.PositiveSmallIntegerField(default=0)
    end_pt = models.PositiveSmallIntegerField(default=0)

    class Meta:
        db_table = "portal_tenhou_aggregated_statistics"

    def player(self):
        return self.tenhou_object.player


class TenhouStatistics(models.Model):
    KYU_LOBBY = 0
    DAN_LOBBY = 1
    UPPERDAN_LOBBY = 2
    PHOENIX_LOBBY = 3

    LOBBIES = [
        [KYU_LOBBY, gettext_lazy("Ippan")],
        [DAN_LOBBY, gettext_lazy("Joukyuu")],
        [UPPERDAN_LOBBY, gettext_lazy("Tokujou")],
        [PHOENIX_LOBBY, gettext_lazy("Houou")],
    ]

    ALL_TIME = 0
    CURRENT_MONTH = 1
    TYPES = [[ALL_TIME, "All time"], [CURRENT_MONTH, "Current month"]]

    tenhou_object = models.ForeignKey(TenhouNickname, on_delete=models.CASCADE, related_name="statistics")
    lobby = models.PositiveSmallIntegerField(choices=LOBBIES)
    stat_type = models.PositiveSmallIntegerField(choices=TYPES, default=ALL_TIME)

    played_games = models.PositiveIntegerField(default=0)
    average_place = models.DecimalField(decimal_places=2, max_digits=10, default=0)

    first_place = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    second_place = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    third_place = models.DecimalField(decimal_places=2, max_digits=10, default=0)
    fourth_place = models.DecimalField(decimal_places=2, max_digits=10, default=0)

    class Meta:
        ordering = ["lobby"]
        db_table = "portal_tenhou_statistics"


class CollectedYakuman(models.Model):
    tenhou_object = models.ForeignKey(TenhouNickname, on_delete=models.CASCADE, related_name="yakumans")
    date = models.DateTimeField()
    log_id = models.CharField(max_length=44)
    yakuman_list = models.CharField(max_length=60)

    class Meta:
        db_table = "portal_collected_yakuman"

    def get_log_link(self):
        return "http://tenhou.net/0/?log={}".format(self.log_id)

    def yakuman_names(self):
        if not self.yakuman_list:
            return YAKUMAN_CONST.get("kazoe")

        yakuman_list = [int(x) for x in self.yakuman_list.split(",")]
        return ", ".join([str(YAKUMAN_CONST.get(x, x)) for x in yakuman_list])


class TenhouGameLog(models.Model):
    FOUR_PLAYERS = 0
    THREE_PLAYERS = 1

    TYPES = [[FOUR_PLAYERS, "Four players"], [THREE_PLAYERS, "Three players"]]

    tenhou_object = models.ForeignKey(TenhouNickname, on_delete=models.CASCADE, related_name="game_logs")

    lobby = models.PositiveSmallIntegerField(choices=TenhouStatistics.LOBBIES)
    place = models.PositiveSmallIntegerField()
    game_length = models.PositiveSmallIntegerField()
    delta = models.SmallIntegerField(default=0)
    rank = models.PositiveSmallIntegerField(
        choices=TenhouAggregatedStatistics.RANKS, null=True, blank=True, default=None
    )
    next_rank = models.PositiveSmallIntegerField(
        choices=TenhouAggregatedStatistics.RANKS, null=True, blank=True, default=None
    )
    game_date = models.DateTimeField()
    game_rules = models.CharField(max_length=20)
    game_players = models.PositiveSmallIntegerField(choices=TYPES, null=True, blank=True)

    class Meta:
        unique_together = ["tenhou_object", "game_date"]
        ordering = ["game_date"]
        db_table = "portal_tenhou_game_log"

    @property
    def game_type(self):
        return self.game_rules[2]

    @property
    def game_end_date(self):
        return self.game_date + timedelta(minutes=self.game_length)

    @property
    def badge_class(self):
        if self.rank < self.next_rank:
            return "success"
        else:
            return "danger"

server/player/tenhou/views.py
from datetime import datetime, timedelta

import pytz
from django.db.models import F, Sum
from django.http import Http404
from django.shortcuts import render
from django.utils import timezone

from player.tenhou.models import CollectedYakuman, TenhouAggregatedStatistics, TenhouGameLog, TenhouNickname
from utils.tenhou.current_tenhou_games import get_latest_wg_games


def get_current_tenhou_games(request):
    return render(request, "tenhou/tenhou_games.html", {})


def get_current_tenhou_games_async(request):
    games = get_latest_wg_games()

    tenhou_objects = TenhouNickname.objects.all().prefetch_related("player")
    player_profiles = {}
    for tenhou_object in tenhou_objects:
        player_profiles[tenhou_object.tenhou_username] = tenhou_object.player

    # let's find players from our database that are playing right now
    found_players = []
    our_players_games = {}

    high_level_games = {}
    high_level_sanma_games = {}

    bot_games = {}

    for game in games:
        for player in game["players"]:
            # we found a player from our database
            if player["name"] in player_profiles:
                found_players.append(player)
                our_players_games[game["game_id"]] = game

            if player["name"].startswith("ⓝ"):
                player["is_bot"] = True
                bot_games[game["game_id"]] = game

            if player["dan"] >= 18:
                if len(game["players"]) == 3:
                    high_level_sanma_games[game["game_id"]] = game
                else:
                    high_level_games[game["game_id"]] = game

    return render(
        request,
        "tenhou/tenhou_games_async.html",
        {
            "our_players_games": our_players_games.values(),
            "high_level_games": high_level_games.values(),
            "high_level_hirosima_games": high_level_sanma_games.values(),
            "bot_games": bot_games.values(),
            "player_profiles": player_profiles,
        },
    )


def latest_yakumans(request):
    yakumans = (
        CollectedYakuman.objects.all().order_by("-date").prefetch_related("tenhou_object", "tenhou_object__player")
    )
    return render(request, "tenhou/latest_yakumans.html", {"yakumans": yakumans})


def tenhou_accounts(request):
    accounts = (
        TenhouAggregatedStatistics.objects.filter(game_players=TenhouAggregatedStatistics.FOUR_PLAYERS)
        .filter(tenhou_object__is_active=True)
        .exclude(played_games=0)
        .order_by("-rank", "-rate", "-pt")
        .prefetch_related("tenhou_object")
        .prefetch_related("tenhou_object__player")
        .prefetch_related("tenhou_object__player__city")
    )
    return render(request, "tenhou/tenhou_accounts.html", {"accounts": accounts})


def games_history(request, year=None, month=None, day=None):
    query_date = timezone.now().date()
    if year and month and day:
        try:
            query_date = datetime(year=int(year), month=int(month), day=int(day), tzinfo=pytz.utc)
        except ValueError:
            raise Http404 from None

    previous_day = query_date - timedelta(days=1)

    games = (
        TenhouGameLog.objects.filter(game_date__date=query_date)
        .filter(game_players=TenhouGameLog.FOUR_PLAYERS)
        .prefetch_related("tenhou_object")
        .prefetch_related("tenhou_object__player")
        .order_by("-game_date")
    )

    rank_changes = TenhouGameLog.objects.filter(
        game_date__date=query_date, game_players=TenhouGameLog.FOUR_PLAYERS
    ).exclude(rank=F("next_rank"))

    return render(
        request,
        "tenhou/games_history.html",
        {
            "query_date": query_date,
            "previous_day": previous_day,
            "games": games,
            "total": games.count(),
            "time_spent": (games.aggregate(Sum("game_length"))["game_length__sum"] or 0) / 60.0,
            "rank_changes": rank_changes,
        },
    )

server/templates/tenhou/_tenhou_player.html
{% load tenhou_helper %}

<a href="https://nodocchi.moe/tenhoulog/#!&name={{ player.name }}" style="color: black" target="_blank">
    {% if player.dan >= 18 %}
        <b>{{ player.dan|display_dan }} R{{ player.rate|display_rate }}</b>
    {% else %}
        {{ player.dan|display_dan }} R{{ player.rate|display_rate }}
    {% endif %}
</a>

<br>

<a href="{{ player.game_link }}" target="_blank">
    {% if player.is_bot %}
        <nobr><b>{{ player.name }}</b></nobr>
    {% else %}
        <nobr>{{ player.name }}</nobr>
    {% endif %}
</a>

{% with player_profiles|get_item:player.name as player_profile %}
    {% if player_profile %}
        (<a href="{% url 'player_details' player_profile.slug %}">{{ player_profile.last_name }}</a>)
    {% endif %}
{% endwith %}

server/templates/tenhou/_tenhou_table.html
{% load i18n tenhou_helper humanize %}

{# Desktop table #}
<div class="table-responsive d-none d-md-block">
    <table class="table mt-2 mb-4 table-bordered">
        <thead>
        <tr>
            <th scope="col" width="20%">
                {% trans 'Start' %}
            </th>
            <th scope="col" width="20%">
                東
            </th>
            <th scope="col" width="20%">
                南
            </th>
            <th scope="col" width="20%">
                西
            </th>
            <th scope="col" width="20%">
                北
            </th>
        </tr>
        </thead>
        <tbody>
        {% for game in games %}
            <tr>
                <td style="vertical-align: middle">
                    {{ game.game_type }} {{ game.start_time|naturaltime }}
                </td>
                {% for player in game.players %}
                    <td>
                        {% include 'tenhou/_tenhou_player.html' %}
                    </td>
                {% endfor %}
                {% if not game.players.3 %}
                    <td>-</td>
                {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

{# Mobile table #}
<div class="table-responsive d-block d-md-none">
    <table class="table mt-2 mb-4 table-bordered">
        <tbody>
        {% for game in games %}
            <tr class="table-success">
                <th scope="col">
                    {% trans 'Start' %}
                </th>
                <td style="align-items : center;">
                    {{ game.game_type }} {{ game.start_time|naturaltime }}
                </td>
            </tr>
            <tr>
                <th scope="col">
                    東
                </th>
                <td>
                    {% with game.players.0 as player %}
                        {% include 'tenhou/_tenhou_player.html' %}
                    {% endwith %}
                </td>
            </tr>
            <tr>
                <th scope="col">
                    南
                </th>
                <td>
                    {% with game.players.1 as player %}
                        {% include 'tenhou/_tenhou_player.html' %}
                    {% endwith %}
                </td>
            </tr>
            <tr>
                <th scope="col">
                    西
                </th>
                <td>
                    {% with game.players.2 as player %}
                        {% include 'tenhou/_tenhou_player.html' %}
                    {% endwith %}
                </td>
            </tr>
            <tr>
                <th scope="col">
                    北
                </th>
                <td>
                    {% if game.players.3 %}
                        {% with game.players.3 as player %}
                            {% include 'tenhou/_tenhou_player.html' %}
                        {% endwith %}
                    {% else %}
                        -
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

server/templates/tenhou/games_history.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Tenhou.net games history' %} {{ query_date|date:SHORT_DATE_FORMAT }}
{% endblock %}

{% block content %}
    <div>
        <p><a href="{% url 'tenhou_games_history' previous_day.year previous_day.month previous_day.day %}">{% trans 'Previous day' %}</a></p>
        <h1>{% trans 'Tenhou.net games history' %} {{ query_date|date:SHORT_DATE_FORMAT }}</h1>

        {% if rank_changes %}
            <h3>{% trans 'Rank changes' %}</h3>
            <div class="table-responsive" style="max-width: 550px">
                <table class="table table-hover mt-4">
                    <thead>
                    <tr>
                        <th scope="col">{% trans 'Player' %}</th>
                        <th scope="col" style="text-align: center">{% trans 'Rank changes' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for game in rank_changes %}
                        <tr>
                            <td>
                                {% with game.tenhou_object.player as player %}
                                    {% include 'common/_player_name.html' %}
                                {% endwith %}
                            </td>
                            <td style="text-align: center">
                                <nobr>
                                    <span class="badge bg-primary">
                                        {{ game.get_rank_display }}
                                    </span>
                                    ->
                                    <span class="badge bg-{{ game.badge_class }}">
                                        {{ game.get_next_rank_display }}
                                    </span>
                                </nobr>
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}

        {% if games %}
            <h3>{% trans 'Records' %}</h3>
            <p>{% trans 'Games' %}: {{ total }}, {% trans 'hours spent' %}: {{ time_spent|floatformat:1 }}.</p>

            <div class="table-responsive">
                <table class="table table-hover mt-4">
                    <thead>
                    <tr>
                        <th scope="col">{% trans 'Player' %}</th>
                        <th scope="col">{% trans 'Rank' %}</th>
                        <th scope="col">{% trans 'Place' %}</th>
                        <th scope="col">{% trans 'Delta' %}</th>
                        <th scope="col">{% trans 'Type' %}</th>
                        <th scope="col">{% trans 'Lobby' %}</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for game in games %}
                        <tr>
                            <td>
                                {% with game.tenhou_object.player as player %}
                                    {% include 'common/_player_name.html' %}
                                {% endwith %}
                            </td>
                            <td>
                                <nobr>{{ game.get_rank_display }}</nobr>
                            </td>
                            <td>
                                {{ game.place }}
                            </td>
                            <td>
                                <nobr>
                                    {% if game.delta > 0 %}
                                        <span class="badge bg-success">{{ game.delta }}</span>
                                    {% elif game.delta == 0 %}
                                        <span class="badge bg-secondary">{{ game.delta }}</span>
                                    {% else %}
                                        <span class="badge bg-danger">{{ game.delta }}</span>
                                    {% endif %}
                                </nobr>
                            </td>
                            <td>
                                {{ game.game_type }}
                            </td>
                            <td>
                                {{ game.get_lobby_display }}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        {% endif %}
    </div>
{% endblock %}

{% block meta_tags %}
    <meta name="description" content="{% trans 'Tenhou.net games history' %} {{ query_date|date:SHORT_DATE_FORMAT }}">
    <meta property="og:description" content="{% trans 'Tenhou.net games history' %} {{ query_date|date:SHORT_DATE_FORMAT }}">
{% endblock %}

server/templates/tenhou/latest_yakumans.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Yakumans from tenhou.net' %}
{% endblock %}

{% block content %}
    <div>
        <h2>{% trans 'Yakumans from tenhou.net' %}</h2>

        <div class="table-responsive">
            <table class="table table-hover mt-4">
                <thead>
                <tr>
                    <th scope="col">{% trans 'Yakuman' %}</th>
                    <th scope="col">{% trans 'Player' %}</th>
                    <th scope="col">{% trans 'Date' %}</th>
                    <th scope="col">{% trans 'Log' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for yakuman in yakumans %}
                    <tr>
                        <td>
                            {{ yakuman.yakuman_names }}
                        </td>
                        <td>
                            {% with yakuman.tenhou_object.player as player %}
                                {% include 'common/_player_name.html' %}
                            {% endwith %}
                        </td>
                        <td>
                            {{ yakuman.date|date:SHORT_DATE_FORMAT }}
                        </td>
                        <td>
                            <a href="{{ yakuman.get_log_link }}" target="_blank">
                                {% trans 'link' %}
                            </a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block meta_tags %}
    <meta name="description" content="{% trans 'Yakumans from tenhou.net' %}">
    <meta property="og:description" content="{% trans 'Yakumans from tenhou.net' %}">
{% endblock %}

server/templates/tenhou/tenhou_accounts.html
{% extends 'base.html' %}
{% load i18n tenhou_helper %}

{% block title %}
    {% trans 'Tenhou accounts' %}
{% endblock %}

{% block content %}
    <div>
        <h2>{% trans 'Tenhou accounts' %}</h2>
        <p>{% trans 'Statistics updated every 5 minutes.'|urlize %}</p>

        <div class="table-responsive">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">{% trans 'Player' %}</th>
                    <th scope="col">{% trans 'Dan' %}</th>
                    <th scope="col">{% trans 'Rate' %}</th>
                    <th scope="col">{% trans 'Tenhou account' %}</th>
                    <th scope="col"></th>
                    <th scope="col">{% trans 'Games' %}</th>
                    <th scope="col">{% trans 'Last played date' %}</th>
                    <th scope="col">{% trans 'City' %}</th>
                </tr>
                </thead>
                <tbody>
                {% for account in accounts %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>
                            {% with account.player as player %}
                                {% include 'common/_player_name.html' %}
                            {% endwith %}
                        </td>
                        <td>
                            <nobr>{{ account.get_rank_display }}</nobr>
                        </td>
                        <td>
                            {% if account.rate %}
                                R{{ account.rate|display_rate }}
                            {% endif %}
                        </td>
                        <td>
                            {{ account.tenhou_object.tenhou_username }}
                        </td>
                        <td>
                            <nobr>{{ account.pt }} / {{ account.end_pt }}pt</nobr>
                        </td>
                        <td>
                            {{ account.played_games }}
                        </td>
                        <td>
                            {{ account.tenhou_object.last_played_date|date:SHORT_DATE_FORMAT }}
                        </td>
                        <td>
                            {% if account.player.city %}
                                <a href="{% url 'city_page' account.player.city.slug %}">{{ account.player.city.name }}</a>
                            {% else %}
                                {% if account.player.is_replacement or account.player.is_hide %}
                                    -
                                {% else %}
                                    {{ account.player.country }}
                                {% endif %}
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

{% block meta_tags %}
    <meta name="description" content="{% trans 'Tenhou accounts' %}">
    <meta property="og:description" content="{% trans 'Tenhou accounts' %}">
{% endblock %}

server/templates/tenhou/tenhou_games.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}
    {% trans 'Current tenhou.net games' %}
{% endblock %}

{% block content %}
    <div id="games-container">
        <p>{% trans 'loading...' %}</p>
    </div>
{% endblock %}

{% block meta_tags %}
    <meta name="description" content="{% trans 'Current tenhou.net games' %}">
    <meta property="og:description" content="{% trans 'Current tenhou.net games' %}">
{% endblock %}

{% block additional_js %}
    <script>
        var games_url = '{% url 'get_current_tenhou_games_async' %}';
        $(document).ready(function () {
            update_games();

            setInterval('update_games()', 30000);
        });

        function update_games() {
            $.get(games_url, function (data) {
                $('#games-container').html(data);
            });
        }
    </script>
{% endblock %}

{% block additional_css %}
    <style>
        th {
            font-weight: normal;
        }

        @media (max-width:768px) {
            th {
                vertical-align: middle !important;
                text-align: center;
                padding: 5px !important;
            }
        }
    </style>
{% endblock %}

server/templates/tenhou/tenhou_games_async.html
{% load i18n tz %}


{% timezone 'Europe/Moscow' %}
    <p class="small">{% trans 'update time' %} {% now 'H:i:s' %} (UTC+3)</p>
{% endtimezone %}

{% if our_players_games %}
    <h2>{% trans 'Current games with our players' %}</h2>
    {% trans 'Games from upperdan and phoenix with portal players.' %}
    {% with our_players_games as games %}
        {% include 'tenhou/_tenhou_table.html' %}
    {% endwith %}
{% endif %}

{% if high_level_games or high_level_hirosima_games %}
    <h2>{% trans 'Current games with high level players' %}</h2>
    <p>{% trans 'Games with 9 dan, 10 dan and tenhou dan players.' %}</p>

    {% if high_level_games %}
        {% with high_level_games as games %}
            {% include 'tenhou/_tenhou_table.html' %}
        {% endwith %}
    {% endif %}

    {% if high_level_hirosima_games %}
        <h3>{% trans 'Sanma' %}</h3>
        {% with high_level_hirosima_games as games %}
            {% include 'tenhou/_tenhou_table.html' %}
        {% endwith %}
    {% endif %}
{% endif %}

{% if bot_games %}
    <h2>{% trans 'Mahjohg bots' %}</h2>

    {% with bot_games as games %}
        {% include 'tenhou/_tenhou_table.html' %}
    {% endwith %}
{% endif %}